project:
  type: website
  output-dir: docs

website:
  title: "Marine Security"
  google-analytics: "G-44VMWXWKWE" 
  site-url: https://polsechub.github.io/marine_security
  #google-analytics: "G-15VG8V8132"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
  cookie-consent:
    type: implied
    style: headline
format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      dark: [superhero, custom.scss]
    css: styles.css

editor: visual

